version: '3.9'

services: 
  app-producto3:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    container_name: mema_app_producto3
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database-producto3
      - mailhog-producto3
  database-producto3:
    image: mysql:8.0
    container_name: mema_db_producto3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mema_transfers_p3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data_p3:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
  phpmyadmin-producto3:
    image: phpmyadmin:5
    container_name: mema_phpmyadmin_producto3
    restart: always
    environment:
      PMA_HOST: database-producto3
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8081:80'
    depends_on:
      - database-producto3
  mailhog-producto3:
    image: mailhog/mailhog
    container_name: mema_mailhog_producto3
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  db_data_p3: